# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CustomAppProto

class Any(object):
    NONE = 0
    GroceryOrderMessage = 1
    HealthStatusMessage = 2
    ResponseMessage = 3
