# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CustomAppProto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ResponseMessage(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ResponseMessage()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsResponseMessage(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ResponseMessage
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ResponseMessage
    def Ts(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ResponseMessage
    def Code(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ResponseMessage
    def Contents(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def ResponseMessageStart(builder): builder.StartObject(3)
def Start(builder):
    return ResponseMessageStart(builder)
def ResponseMessageAddTs(builder, ts): builder.PrependFloat32Slot(0, ts, 0.0)
def AddTs(builder, ts):
    return ResponseMessageAddTs(builder, ts)
def ResponseMessageAddCode(builder, code): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(code), 0)
def AddCode(builder, code):
    return ResponseMessageAddCode(builder, code)
def ResponseMessageAddContents(builder, contents): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(contents), 0)
def AddContents(builder, contents):
    return ResponseMessageAddContents(builder, contents)
def ResponseMessageEnd(builder): return builder.EndObject()
def End(builder):
    return ResponseMessageEnd(builder)